#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
print('-=-='*10)
num = int (input('\033[1;35m Digite um número para ver sua tabuada:\033[m'))
print('-=-='*10)
print('{} x {} = {}'.format(num,1,num * 1))
print('{} x {} = {}'.format(num,2,num * 2))
print('{} x {} = {}'.format(num,3,num * 3))
print('{} x {} = {}'.format(num,4,num * 4))
print('{} x {} = {}'.format(num,5,num * 5))
print('{} x {} = {}'.format(num,6,num * 6))
print('{} x {} = {}'.format(num,7,num * 7))
print('{} x {} = {}'.format(num,8,num * 8))
print('{} x {} = {}'.format(num,9,num * 9))
print('{} x {} = {}'.format(num,10,num * 10))
